name: base_class_gen
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # fmp gen
  source_gen: ^1.4.0
  analyzer: ^5.0.0
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  build: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
